# fly.toml app configuration file generated for www-4bea25fc-4478-43af-bdb4-023293454341-client on 2024-06-20T09:30:27+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'www-4bea25fc-4478-43af-bdb4-023293454341-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
