# fly.toml app configuration file generated for www-4bea25fc-4478-43af-bdb4-023293454341-server on 2024-06-20T09:30:16+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'www-4bea25fc-4478-43af-bdb4-023293454341-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
